### ISSUE TITLE
There is a problem connecting setup.py with cython module in the updated version of phaser.r.

### ISSUE THREAD

**Issue by everestial** [secastel/phaser#16]
@secastel 

--output_orphans options isn't working. I looked into the python file and that option isn't there. I am not using this at the moment but just picking something that might be useful to others.

Also, with the updated version of phaser you have included 'setup.py'. I have my cython module installed but I am getting the following error:
Traceback (most recent call last):
File "setup.py", line 2, in
from Cython.Build import cythonize
ImportError: No module named 'Cython'

The old version didn't quite needed that.

**Comment by secastel** [comment]
Hi,
Thanks for letting me know about output_orphans. I have to look into it, but it’s possible that this functionality was removed at some point but that the arguments / manual hasn’t been updated yet.

In terms of the problem with Cython, I just tried here with a fresh install and didn’t have a problem. What version of python and cython are you using? The new version uses cython to compile the module that assigns reads to alleles, this is a really rate limiting step, so the speed increase from cython compilation helps to reduce runtimes.

One thing you could try is changing “Cython.build” to “cython.build” in setup.py. It’s possible that whatever versions you are running don’t like the capitalization… but no idea really.

Please let me know if you are able to get it running, as if there is a problem I’d like to try to get it fixed.

**Comment by everestial** [comment]
@secastel 
I had actually tried that, but it the same error message:

    `$ python /home/everestial007/phaser-master_New/phaser/setup.py build_ext --inplace
    Traceback (most recent call last):
      File "/home/everestial007/phaser-master_New/phaser/setup.py", line 2, in <module>
        from cython.Build import cythonize
    ImportError: No module named 'cython'`

But, I have my `cython` installed and verified it.
`$ cython
Cython (http://cython.org) is a compiler for code written in the
Cython language.  Cython is based on Pyrex by Greg Ewing.

Usage: cython [options] sourcefile.{pyx,py} ...

Options:
  -V, --version                  Display version number of cython compiler
........................`

**Comment by secastel** [comment]
Hmm, I'm not exactly sure what is going on here. The new version of phASER has been built successfully on many different platforms. You need to ensure that cython can be imported from python. If you have it installed properly you should be able to do this. You can test it out by launching an interactive session of python and simply typing "import cython". It should be able to import without error. On all the systems I have tested, after installing cython using pip ("pip install cython"), I am able to import it and build phaser.

**Comment by secastel** [comment]
One possibility is that you installed cython for a different version of python than what you are using to run phASER.

**Comment by everestial** [comment]
I tried ipython just to test it and yes 'cython' is installed. I also trie pip install and it already shows the installation. I think the issue is I am using python 3.5 in my computer and cython you have is only able to work with python 2.7. Just assuming (since I see that phaser is by default run with python 2).

**Comment by secastel** [comment]
This is likely the problem. **phASER is only compatible with python 2.7.X.** You need to ensure that cython is installed for this version of python. In the case that you have multiple installs of python there is likely a way to direct pip to install for the appropriate python version. Once you have cython installed for python 2.7 it should work.

**Comment by everestial** [comment]
I am confident that version of python is an issue. I will see how I can fix it. I am little surprised why are we still using python 2 when version 3 is out there and I have heard recommendation to use 3. I am biologist, perhaps you can give me some info on this.
Also, can you look into the another issue I submitted.

Thanks,

**Comment by secastel** [comment]
Version 3 of python made significant changes to the language that were not taken well by the development community. This lead to the simultaneous development of version 2.X and 3.X. Many pieces of software still work primarily in python 2.X because of compatibility issues. Python 3 is however getting better, so I expect at some point I will port phASER over, but no time in the immediate future.

I will respond to your other issue in a few days. I am currently traveling for the holidays.
