### ISSUE TITLE
"|" pipe symbol in contig /chromosome ID causes crash: Solution

### ISSUE THREAD

**Issue by mscharmann** [secastel/phaser#18]
Hello,
I use Trinity denovo assembled transcriptome contigs as the reference, and Trinity names its contigs e.g. "TR72377|c0_g1_i1". Unfortunately, "samtools view -h X.bam TR72377|c0_g1_i1: "
whill choke on this because the "|" symbol in the contig name is interpreted as a functional pipe.
The solution is to wrap the contig ID in hyphens, which eleviates the issue and does not affect contig names that do not contain the pipe.

I suggest to modify phaser.py:

orig. line 1070:
error_code = subprocess.call("samtools view -h "+bam+" "+chrom+": | samtools view -Sh "+samtools_arg+" -L "+bed_out+" -q "+mapq+" - | "+args.python_string+" "+return_script_path()+"/call_read_variant_map.py --baseq "+str(args.baseq)+" --splice 1 --isize_cutoff "+str(isize)+" --variant_table "+mapper_out+" --o "+mapping_result.name, stderr=devnull, stdout=devnull, shell=True);

replace this line by the hyphenated version:
error_code = subprocess.call("samtools view -h "+bam+" '"+chrom+"': | samtools view -Sh "+samtools_arg+" -L "+bed_out+" -q "+mapq+" - | "+args.python_string+" "+return_script_path()+"/call_read_variant_map.py --baseq "+str(args.baseq)+" --splice 1 --isize_cutoff "+str(isize)+" --variant_table "+mapper_out+" --o "+mapping_result.name, stderr=devnull, stdout=devnull, shell=True);

Thanks!

**Comment by secastel** [comment]
Hi, this makes sense, thank you for catching the problem. I will add it to the main branch. If you make this change does it fix your previous issue #17  ?
