### ISSUE TITLE
Haplotype phase of the homozygous allele

### ISSUE THREAD

**Issue by everestial** [secastel/phaser#20]
@secastel 

I just wanted to highlight a suggestion that could be incorporated into phaser given your time allows. 
`phaser` is designed mainly to generate haplotypes only for the heterozygous sites. But, from a biological stand point I think it would be more helpful to include an option, where we can extract the haplotypes even if the allele is homozgous variant, given the RB phased read to supports it. And, I think there are most cases like that. 

**An example something like this:**

    chr       pos        id        ref        alt          GT        PG      Phase_Block_index
    2          35          .          A         G            0/1       0|1          50
    2          71          .          C         A            1/1       1/1          .
    2          85          .          C         G            0/1       1|0          50
    2          97          .          G        T,A          1/2       2|1          50
    2          103        .          T         C             0/0       0/0          .
    2          107        .          C        A,G          0/1       0|1          50

So, for the above example `phaser` is designed to just generate haplotype from the heterozygous loci, which will be **A-G-A-C & G-C-T-A**. But, if the homozygous alternate **genotype (1/1) or (0/0)** is supported by the RBphased bam file there should be an option to get that **- i.e haplotypes A-A-G-A-T-C & G-A-C-T-T-A and also the update of phase_block_index and PG.** These kind of haplotypes are going to be more helpful in population genetics analyses. I think it would make phaser more helpful tool.

**Comment by iranmdl** [comment]
Hi there!
Any news on this? I'm also quite interested in what @everestial has pointed out :)

**Comment by secastel** [comment]
Sorry for the delay, it's been an extremely busy month.

To address this I could add an option that will automatically set the phase block index of homozygous variants in the outputted VCF to any preceding index. In this case reads are completely uninformative as there is no phase to be detected. In cases where a homozygous variant is found between two phase blocks the homozygous variant would be assigned to the phase block upstream of it.

Please let me know if you think this would be an acceptable solution.

**Comment by secastel** [comment]
Getting back to this. I think you are missing something here:

> But, there is a catch - you would want to assign the index from the block (preceding or proceeding) whose reads were connected to that homozygous variant.

It doesn't make sense to link homozygous variants to heterozygous variants if a read overlaps them both. The reads are uninformative. It would be a completely arbitrary measure. The only thing it would indicate is that the variants are close enough to one another that a read can overlap both - nothing more.

Looking at the code, I can add an option that sets the phase block index of homozygous variants in the output VCF to any preceding phase block, but that is it. Homozygous variants would not be included in any of the other output files (e.g. haplotypes.txt).

**Comment by everestial** [comment]
Hi @secastel : Any update on this issue.

From what I am trying to do with my data (pop gen analyses), it would help me to have a any attached ReadBack phased HomVar inside the haplotype block, to compare the association of homVar between different samples and between populations. The site could be homVar (2|2) in one sample (population) but HetVar (2|0) in several other individuals or population.

For eg:  for PI=25        A-C-G-**T**-C-T-**G**-T-A-C-G-**G**-T-A
                                    C-T-A-**T**-A-G-**G**-A-C-G-A-**G**-A-C

is better than:     A-C-G-C-T-T-A-C-G-T-A
                           C-T-A-A-G-A-C-G-A-A-C

But, if you made the proposed changes I should be happy if those information are updated at least in `PG and PI`

Thank you !

**Comment by secastel** [comment]
Hi there. I haven't implemented the suggested change yet, because no one got back to me to let me know if it would solve the problem.

I agree that it makes sense to include homozygous variants that are within a local phase block in that phase block. This should be an easy change. I am in the process of putting together a big release, that I am hoping to have out in the next 2 weeks, so I will include this feature in that release.

Stay tuned.

**Comment by everestial** [comment]
ok @secastel . Please let me know if the issue gets fixed.
Thanks much

**Comment by everestial** [comment]
@secastel 
Any update on this.

**Comment by secastel** [comment]
I'm now looking at what would be involved in implementing this. The way phASER is written it completely disregards homozygous variants when running. This means that the only solution I can offer you is when generating the outputted VCF, for homozygous variants to be assigned to the last haplotype block that was outputted, provided it was on the same chromosome. I'm not able to implement what you asked for, which is to assign homozygous variants to a haplotype block if their are flanked by variants that are found within that haplotype block. If you absolutely need this functionality you could make your own script that processes the outputted VCF and does this. Please let me know if you would like to implement what I suggested.

**Comment by everestial** [comment]
I think adding the `homVAR` in the head or tail of the haplotype block wouldn't help much. I am doing between sample comparisons and this functionality would have helped. 
It's ok, I hope I could hack into `phaser` to work this out, but I suppose with my skills I am only to going to make it worse. lets see.

**Comment by everestial** [comment]
If you can, can you point me inside your python code, where you start testing/joining the haplotypes.

**Comment by secastel** [comment]
I don't think you will be able to modify the phASER code to do this - if it were trivial I would have done it myself. I think the best approach would be to make a script that processes VCF outputted by phASER, and updated homozygous variants with a haplotype block if they are found in between two phased heterozygous variants.

**Comment by everestial** [comment]
Yup, that would work. Will try that sometime next week.

**Comment by everestial** [comment]
Just had chance to prepare a python parser to solve this issue. Share it if it helps.
Thanks,

**Comment by iranmdl** [comment]
Hello @everestial , would be nice if you can share the code :)

**Comment by everestial** [comment]
Hi, @iranmdl : Here is the python program, https://github.com/everestial/Update_HomVar
For, now it is designed to take the PI from the former haplotype blocks -> and insert the PI and update PG into the proceeding Homozygous Variants (including 0/0). It also compares if the HomVar are within the same chromosome. The only limitation at the moment is that it will not start updating the HomVar until it finds the very first HaplotypeBlock, thus loosing very little information.

If there are some other changes you would want me to add, I should be able to do it. :)

**Comment by everestial** [comment]
If you don't want to update PI and PG for 0/0, I can add some more functions to it. Just let me know.
