### ISSUE TITLE
error running phaser, sorry...

### ISSUE THREAD

**Issue by evigorito** [secastel/phaser#23]
Hi Stephane,
This tool is great and very well explained for a non-expert such as myself, many thanks indeed!!!
I have a problem which I hope you can help me, running your example data set I tried the following command after having succeed with the first one

$python /scratch/ev250/bin/phaser/phaser_gene_ae/phaser_gene_ae.py --haplotypic_counts phaser_test_case.haplotypic_counts.txt --features hg19_ensembl.bed --o phaser_test_case_gene_ae.txt --no_gw_phase 0

However, I get the following error

##################################################
          Welcome to phASER Gene AE v1.1
  Author: Stephane Castel (scastel@nygenome.org)
##################################################

#1 Loading features...
#2 Loading haplotype counts...
Traceback (most recent call last):
  File "/scratch/ev250/bin/phaser/phaser_gene_ae/phaser_gene_ae.py", line 127, in <module>
    main();
  File "/scratch/ev250/bin/phaser/phaser_gene_ae/phaser_gene_ae.py", line 65, in main
    df_haplo_counts = pandas.DataFrame.from_csv(args.haplotypic_counts, sep="\t", index_col=False);
  File "/scratch/ev250/bin/PYTHON/lib/python2.7/site-packages/pandas/core/frame.py", line 1231, in from_csv
    infer_datetime_format=infer_datetime_format)
  File "/scratch/ev250/bin/PYTHON/lib/python2.7/site-packages/pandas/io/parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/scratch/ev250/bin/PYTHON/lib/python2.7/site-packages/pandas/io/parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/scratch/ev250/bin/PYTHON/lib/python2.7/site-packages/pandas/io/parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "/scratch/ev250/bin/PYTHON/lib/python2.7/site-packages/pandas/io/parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/scratch/ev250/bin/PYTHON/lib/python2.7/site-packages/pandas/io/parsers.py", line 1436, in __init__
    self._set_noconvert_columns()
  File "/scratch/ev250/bin/PYTHON/lib/python2.7/site-packages/pandas/io/parsers.py", line 1501, in _set_noconvert_columns
    _set(self.index_col)
  File "/scratch/ev250/bin/PYTHON/lib/python2.7/site-packages/pandas/io/parsers.py", line 1476, in _set
    x = names.index(x)
ValueError: False is not in list

which I cannot figure out, could you please help me to troubleshoot this? many thanks in advance

Elena

**Comment by secastel** [comment]
Hi there! Glad that you are finding the tool useful. Sorry about the bug - not exactly sure what is causing it. Would you mind zipping the file "phaser_test_case.haplotypic_counts.txt" and uploading it here? That way I can try to reproduce the problem and figure out what is going on.

Stephane

**Comment by evigorito** [comment]
[phaser_test_case.haplotypic_counts.txt.gz](https://github.com/secastel/phaser/files/789878/phaser_test_case.haplotypic_counts.txt.gz)

Thanks very much for your quick response. I dont know if this can help, in line 65 on phaser_gene_ae.py
says:
df_haplo_counts = pandas.DataFrame.from_csv(args.haplotypic_counts, sep="\t", index_col=False);
If I change index_col=0, it reads the data.frame and I can move to step #3. However, I then get the following error
#my command:
python /scratch/ev250/bin/phaser/phaser_gene_ae/phaser_gene_ae.py --haplotypic_counts phaser_test_case.haplotypic_counts.txt --features hg19_ensembl.bed --o phaser_test_case_gene_ae.txt --no_gw_phase 0

#output
##################################################
          Welcome to phASER Gene AE v1.1
  Author: Stephane Castel (scastel@nygenome.org)
##################################################

#1 Loading features...
#2 Loading haplotype counts...
#3 Generating feature level haplotypic counts...
Traceback (most recent call last):
  File "/scratch/ev250/bin/phaser/phaser_gene_ae/phaser_gene_ae.py", line 127, in <module>
    main();
  File "/scratch/ev250/bin/phaser/phaser_gene_ae/phaser_gene_ae.py", line 71, in main
    chrom = str(row['contig']);
  File "/scratch/ev250/bin/PYTHON/lib/python2.7/site-packages/pandas/core/series.py", line 603, in __getitem__
    result = self.index.get_value(self, key)
  File "/scratch/ev250/bin/PYTHON/lib/python2.7/site-packages/pandas/indexes/base.py", line 2183, in get_value
    raise e1
KeyError: 'contig'

Many thanks in advance, I am so much looking forward to using your tool!

Best wishes,

Elena

**Comment by secastel** [comment]
Thanks for sending the file. Your modification to the code will not work, so please put it back to what it was originally. I was able to run the gene AE step with no problem using the original code:

python phaser/phaser_gene_ae/phaser_gene_ae.py --haplotypic_counts phaser_test_case.haplotypic_counts.txt --features hg19_ensembl.bed --o phaser_test_case_gene_ae.txt --no_gw_phase 0

##################################################
          Welcome to phASER Gene AE v1.1
  Author: Stephane Castel (scastel@nygenome.org)
##################################################

#1 Loading features...
#2 Loading haplotype counts...
#3 Generating feature level haplotypic counts...
#4 Outputting feature haplotype counts...

I'm wondering if it is a problem with your Pandas installation? Can you please check what version you have with the following python code:

>>> import pandas
>>> pandas.__version__
u'0.18.1'

If you have an older version than what you see above then I suggest you try updating Pandas. This will also be good for me to know, as I can include it in the readme. Thanks again, and sorry for the problems!

**Comment by evigorito** [comment]
Hi Stephane,

Many thanks for your help. The pandas version I have is:

pandas: 0.19.2

Best wishes,

Elena
________________________________

**Comment by secastel** [comment]
I was able to reproduce the issue. It looks like there was a bug introduced in the most recent version of Pandas. I have updated the code to fix this issue, so if you pull the latest version you should be all set. Sorry for the problem, and thanks for helping me identify it!

**Comment by evigorito** [comment]
Thanks to you!!!!

All the best,

Elena
________________________________
