### ISSUE TITLE
Improve phased GT in F1 hybrids using partially phased data (PG) generated using pHASER

### ISSUE THREAD

**Issue by everestial** [secastel/phaser#26]
Hi Secastel,

This isn't an issue, but an update. I recently finished writing a python3 script to improve the phased GT of the F1 hybrid. I wanted to connect with people who might be having similar problems and let them know about this tool. This script and details aren't completely clean yet, but should be able to run given the python3 and required modules are available.

https://github.com/everestial/pHASE-Stitcher

Thanks,

**Comment by secastel** [comment]
That is great, thanks for sharing! I will make sure to forward to anyone who is interested in doing this. Good luck!
