### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by paulhager** [secastel/phaser#27]
Hi, I've been using phASER the past couple of days and have been super happy with the results, but after trying to incorporate DNAseq reads in addition to RNAseq reads into our haplotype calling with phASER we are constantly getting out of memory errors in thread 13. phASER works fine with the example data you provided in your tutorial, as well as with just our RNAseq data, but as soon as we use RNAseq reads and DNAseq reads we get out of memory errors.

phASER manages to map reads to variants for both RNAseq and DNAseq reads, but during the processing step it always throws the following error:

processing mapped reads...
          using alignment score cutoff of 115
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 325, in _handle_workers
    pool._maintain_pool()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 229, in _maintain_pool
    self._repopulate_pool()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 222, in _repopulate_pool
    w.start()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

At first I thought it was just my local computer not having enough memory (only 6GB free), but even after letting it run on our cluster which has around 50 GB memory free, it still threw that error. The command I used to call phASER was:

python /home/ibis/paul.hager/phaser/phaser/phaser.py --vcf /home/ibis/paul.hager/SCN306/Phasing/GATKPhaseByTransmission/SL154375.GATKTransmissionPhased.vcf.gz --bam /home/ibis/paul.hager/SCN306/Phasing/RNAseq/rnanz1_1-2_S13_R1_001_val_1.fq.Aligned.out.sort.bam,/home/ibis/paul.hager/SCN306/IBIS_WGS/SCN306pat/HMNNHCCXX_s1_1_GSLv3-7_49_SL154375.filtered.fastq_mem.sorted.mergedAll.realigned.recal.bam --paired_end 1,1 --mapq 255,60 --baseq 10 --sample SL154375 --blacklist /home/ibis/paul.hager/phaser/testData/hg19_hla.bed --haplo_count_blacklist /home/ibis/paul.hager/phaser/testData/hg19_haplo_count_blacklist.bed --threads 4 --o /home/ibis/paul.hager/SCN306/Phasing/Phaser/rnanz1_2/phaserSL154375_trioPhase_r12 --id_separator - --unique_ids 1

Do you have any idea what might be causing this error?

Thanks for your help!

**Comment by secastel** [comment]
Hi Paul, glad to hear that phASER has been working for you. I think your problem should be easy to fix. What sort of DNA-seq reads are you using? Are they WGS reads? How big is the input BAM file? If it is huge (e.g. 30x WGS = > 100GB) then I would suggest trying to run one chromosome at a time. If you have a cluster you can submit multiple jobs, one per chromosome. To run only a single chromosome add the --chr option when running.

**Comment by paulhager** [comment]
Oh, yeah. The DNA-seq redas BAM file is over 200GB. When running individual chromosomes it works. Thanks!

**Comment by secastel** [comment]
Glad to hear. Good luck! Closing the issue.
