### ISSUE TITLE
phaser can phase indel ?

### ISSUE THREAD

**Issue by zeronot** [secastel/phaser#28]
HI ,
   phaser  can support to phase indel  ??
  I find  ReadBackedPhasing just can phase SNV....but I  wanna phase indel and SNV . 
  my data is  human DNA array sequencing data   .

**Comment by secastel** [comment]
Yes, phASER can phase indels if the "--include_indels 1" argument is provided. However, please be aware that in general the phasing quality of indels (especially large ones) is lower due to mapping problems.

**Comment by lidd7** [comment]
@secastel 
HI ,
1. my data is human DNA  illumina array sequencing data , it's ok ? 
2. how 'phase.py'  works ? can you give some details ?
3.first I use GATK-ReadBackedPhasing to phase snv ,and got a VCF ,then I phase snv and indel together  if the indel has the common(same) read with known phased snv marked by ReadBackedPhasing, I am not sure it's right ?

**Comment by secastel** [comment]
Any DNA-sequencing data should be fine.

Please refer to the documentation page found here: https://github.com/secastel/phaser/tree/master/phaser which describes in detail the use of phASER, required input files, and options.
