### ISSUE TITLE
ignoring variants without PASS flag

### ISSUE THREAD

**Issue by inti** [secastel/phaser#3]
Hi,
Thanks for the work on this! 

it seems that phaser.py ignores variants on the --vcf file which do not have the PASS flag. This is somewhat restrictive sine one could not have it at all or have other flags. I think it is worth stating on the documentation that only variants with the PASS flag are considered.

Cheers

**Comment by secastel** [comment]
Hi there,
This is correct - in keeping with standard in many pieces of software we decided to exclude any sites that do not contain "PASS" in their filter field.

This behavior can be changed using the "--pass_only 0" argument.

I have updated the README to hopefully make this more clear.

Thanks for bringing this to our attention, and hope you find the software useful.
