### ISSUE TITLE
Issues with the reference genome update（hg19 to hg38）

### ISSUE THREAD

**Issue by clsteam** [secastel/phaser#43]
Considering that the reference genome has been updated, now I want to use the hg38 reference genome for analysis, may I ask that can this tool be transplanted to hg38 ? If so, I notice that you only provide  files related to hg19  (such as 'Useful files' : [hg19_hla.bed.gz](ftp://ftp.nygenome.org/sec/phaser/annot_files_v100/hg19_haplo_count_blacklist.bed.gz) and [hg19_haplo_count_blacklist.bed.gz](ftp://ftp.nygenome.org/sec/phaser/annot_files_v100/hg19_haplo_count_blacklist.bed.gz)), could you please update these files to hg38 .

**Comment by secastel** [comment]
Thank you for pointing this out. I have added the appropriate hg38 annotations to each of the readme pages.
