### ISSUE TITLE
Phaser freezing after retrieving reads

### ISSUE THREAD

**Issue by clarepacini** [secastel/phaser#49]
Hi,

I am running phaser on a bam of around 6Gb and it is completing step 2 but never making it to step 3. I have been able to successfully run the example in the tutorial. This is the end of the log file:
[samopen] SAM header is present: 25 sequences.
               completed chromosome Y...
[samopen] SAM header is present: 25 sequences.
               completed chromosome 3...
[samopen] SAM header is present: 25 sequences.
               completed chromosome 2...
[samopen] SAM header is present: 25 sequences.
               completed chromosome 5...
[samopen] SAM header is present: 25 sequences.
               completed chromosome 9...
[samopen] SAM header is present: 25 sequences.
               completed chromosome X...
[samopen] SAM header is present: 25 sequences.
               completed chromosome 6...
[samopen] SAM header is present: 25 sequences.
               completed chromosome 8...
[samopen] SAM header is present: 25 sequences.
               completed chromosome 13...
[samopen] SAM header is present: 25 sequences.
               completed chromosome 10...
[samopen] SAM header is present: 25 sequences.
               completed chromosome 15...
[samopen] SAM header is present: 25 sequences.
               completed chromosome 14...
               completed chromosome 1...
               completed chromosome 18...
               completed chromosome 11...
               completed chromosome 16...
               completed chromosome 17...
               completed chromosome 19...
               completed chromosome 12...

It has been running for over an hour (and on a larger file over 2 days still at this point). Any ideas as to what might be causing this would be great!

Thanks,
Clare

**Comment by clarepacini** [comment]
I was running it on a cluster but nothing was happening. I found it was actually a problem with the bam file, it has now run successfully (and quickly!). It was just unfortunate phaser didn't give an error but got stuck not doing anything! Thanks!

**Comment by secastel** [comment]
Great, glad you were able to solve the issue.
