### ISSUE TITLE
No alignment score in BAM file

### ISSUE THREAD

**Issue by rahulk87** [secastel/phaser#56]
Hi,

I am running phaser and getting an error that there is no alignment score in the RNA-seq BAM file. I was wondering, if is there a way to run phaser without considering alignment score?

Many thanks,
Rahul

**Comment by secastel** [comment]
Hi Rahul,
Sorry for the delayed response. You can run phASER without alignment score by adding the argument "--as_q_cutoff 0". A word of caution, including AS will dramatically improve phasing quality from RNA-seq data. I'd suggest using using an RNA-seq alignment tool that includes alignment score.

Stephane

**Comment by rahulk87** [comment]
Thanks Stephane, very helpful!!
