### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str

### ISSUE THREAD

**Issue by deb0612** [secastel/phaser#63]
Dear sir,
I ran "python phaser/phaser/phaser.py --vcf NA06986.vcf.gz --bam NA06986.2.M_111215_4.bam --paired_end 1 --mapq 255 --baseq 10 --sample NA06986 --blacklist hg19_hla.bed --haplo_count_blacklist hg19_haplo_count_blacklist.bed --threads 4 --o test_case"  but show information below: 

##################################################
              Welcome to phASER v1.1.1
  Author: Stephane Castel (scastel@nygenome.org)
  Updated by: Bishwa K. Giri (bkgiri@uncg.edu)
##################################################

Completed the check of dependencies and input files availability... 

STARTED "Read backed phasing and ASE/haplotype analyses" ... 
    DATE, TIME : 2020-08-23, 01:07:21
#1. Loading heterozygous variants into intervals...
Processing sample named NA06986
    using all the chromosomes ...
    removing blacklisted variants and processing VCF...
#1b. Loading haplotypic count blacklist intervals...
Traceback (most recent call last):
  File "phaser/phaser/phaser.py", line 2358, in <module>
    main();
  File "phaser/phaser/phaser.py", line 170, in main
    parse_sample(sample_name, map_sample_column, args.bam, args.o, contig_ban)
  File "phaser/phaser/phaser.py", line 235, in parse_sample
    for line in raw_interval.split("\n"):
TypeError: a bytes-like object is required, not 'str

**Comment by jegalle** [comment]
Hi

I was wondering how this problem was fixed. I'm having this issue atm:
`Traceback (most recent call last):
  File "/opt/phaser/phaser/phaser.py", line 2358, in <module>
    main();
  File "/opt/phaser/phaser/phaser.py", line 170, in main
    parse_sample(sample_name, map_sample_column, args.bam, args.o, contig_ban)
  File "/opt/phaser/phaser/phaser.py", line 262, in parse_sample
    start_time, vcf_out, sample_out_path, last_chr=True, pi_block_value = 0)
  File "/opt/phaser/phaser/phaser.py", line 546, in process_vcf
    alignment_scores = map(int,[x for x in subprocess.check_output("set -euo pipefail && "+"cut -f 5 "+" ".join(result_files), shell=True, executable='/bin/bash').split("\n") if x != ""]);
TypeError: a bytes-like object is required, not 'str'
`

**Comment by jegalle** [comment]
Nevermind! I ran phaser in python3, running in python2.7 fixed the issue.

**Comment by secastel** [comment]
Great, glad you were able to sort this out!
