### ISSUE TITLE
Retrieve parent of origin for haplotypes

### ISSUE THREAD

**Issue by vilperte** [secastel/phaser#66]
Hello,

I was wondering if it is possible to retrieve the information from which parent the haplotypeA and haplotypeB belong to from each variant? From the information below, you don't really get that unless you go manually position by position and check back on the parent haplotypes.

contig | start | stop | variants | variantCount | variantsBlacklisted | variantCountBlacklisted | haplotypeA | haplotypeB | aCount | bCount | totalCount | blockGWPhase | gwStat | max_haplo_maf
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Pt | 27556 | 27651 | Pt_27556_G_C,Pt_27579_G_A,Pt_27651_A_G | 3 |   | 0 | G,G,A | C,A,G | 45 | 8 | 53 | 0\|1 | 1 | 0
Mt | 469575 | 469928 | Mt_469575_G_A,Mt_469615_G_A,Mt_469830_G_A,Mt_469851_G_A,Mt_469928_G_A | 5 |   | 0 | G,G,G,G,G | A,A,A,A,A | 40 | 98 | 138 | 1\|0 | 1 | 0
1 | 965192 | 965216 | 1_965192_A_G,1_965216_G_A | 2 |   | 0 | A,G | G,A | 8 | 3 | 11 | 0\|1 | 1 | 0
1 | 2057987 | 2058330 | 1_2057987_A_G,1_2058330_G_A | 2 |   | 0 | A,G | G,A | 275 | 71 | 346 | 1\|0 | 1 | 0
1 | 3745325 | 3745384 | 1_3745325_A_T,1_3745372_A_C,1_3745384_G_T | 3 |   | 0 | A,A,G | T,C,T | 39 | 90 | 129 | 0\|1 | 1 | 0
1 | 3944522 | 3944576 | 1_3944522_T_A,1_3944576_A_C | 2 |   | 0 | T,A | A,C | 189 | 53 | 242 | 1\|0 | 1 | 0

In the end I get this information for gene level ASE, but still can't tell from which parent the aCount and bCount belong to.

contig | start | stop | name | aCount | bCount | totalCount | log2_aFC | n_variants | variants | gw_phased
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 2056177 | 2063842 | transcript:g6744.t1.mrna1 | 71 | 275 | 346 | -1.95354 | 2 | 1_2057987_A_G,1_2058330_G_A | 1
1 | 2056177 | 2063842 | transcript:g6744.t2.mrna1 | 71 | 275 | 346 | -1.95354 | 2 | 1_2057987_A_G,1_2058330_G_A | 1
1 | 4429469 | 4432731 | transcript:g6954.t1.mrna1 | 22 | 68 | 90 | -1.62803 | 2 | 1_4432473_T_G,1_4432608_A_C | 0
1 | 4471409 | 4477264 | transcript:g6959.t1.mrna1 | 10 | 35 | 45 | -1.80735 | 1 | 1_4477251_A_T | 0
1 | 5644643 | 5663507 | transcript:g7066.t2.mrna1 | 9 | 76 | 85 | -3.078 | 2 | 1_5655537_A_G,1_5655576_C_T | 1

Thanks for the help.

**Comment by secastel** [comment]
I believe you can retrieve this information from the "blockGWPhase" column in the haplotypic_counts output. In the case of the first row, I believe block A corresponds to parent 0 in the VCF and block B corresponds to parent 1. For the second row, block A corresponds to parent 1 and block B corresponds to parent 0. Please double check this versus your manually process to make sure I'm remember correctly though.

**Comment by zhang-jiankun** [comment]
Hi @secastel ,

As far as I understand, in the haplotypic_counts output, haplotype A corresponds to reference allele and haplotype B correponds to alternative allele. In the gene_ae output, aCount corresponds to paternal genome and bCount corresponds to maternal genome. Is my understanding of this correct?

Jiankun
