### ISSUE TITLE
Error running phaser

### ISSUE THREAD

**Issue by Arkosen** [secastel/phaser#71]
Hi
I tried compiling phaser using the instructions laid out in the how-to section.  I got the following output

(base) -bash-4.2$ python setup.py build_ext --inplace
Compiling read_variant_map.py because it changed.
[1/1] Cythonizing read_variant_map.py
/iblm/netapp/home/asen/.local/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /iblm/netapp/home/asen/phaser/phaser/read_variant_map.py
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'read_variant_map' extension
creating build
creating build/temp.linux-x86_64-3.7
/iblm/netapp/home/asen/myconda/bin/x86_64-conda_cos6-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /iblm/netapp/home/asen/myconda/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /iblm/netapp/home/asen/myconda/include -fPIC -I/iblm/netapp/home/asen/myconda/include/python3.7m -c read_variant_map.c -o build/temp.linux-x86_64-3.7/read_variant_map.o
x86_64-conda_cos6-linux-gnu-gcc -pthread -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/iblm/netapp/home/asen/myconda/lib -L/iblm/netapp/home/asen/myconda/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/iblm/netapp/home/asen/myconda/lib -L/iblm/netapp/home/asen/myconda/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/iblm/netapp/home/asen/myconda/lib -Wl,-rpath-link,/iblm/netapp/home/asen/myconda/lib -L/iblm/netapp/home/asen/myconda/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /iblm/netapp/home/asen/myconda/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /iblm/netapp/home/asen/myconda/include build/temp.linux-x86_64-3.7/read_variant_map.o -o /iblm/netapp/home/asen/phaser/phaser/read_variant_map.cpython-37m-x86_64-linux-gnu.so

Then I tried to running phaser.py and got the following error.

FATAL ERROR: Read Variant Mapper module must be compiled by running 'python setup.py build_ext --inplace'.

which suggest that the compilation wasnt correct.

Any suggestions?

Thanks

**Comment by secastel** [comment]
Glad to hear that worked for you. As for your followup question, you can look in the outputted VCF or the haplotypes.txt file to determine which variants were phased. You'll need to do your own processing of those outputs to get the answer.
