### ISSUE TITLE
 software is suitable for  ChIP-seq data

### ISSUE THREAD

**Issue by TaoHJiang** [secastel/phaser#73]
Dear Developer,

I wonder if this software is suitable for ASB search. 

Thank you!

**Comment by secastel** [comment]
Hello,

In theory I don't see a reason why it wouldn't work, however, it is not been benchmarked at all for this use case. There may be parameters that need to be tweaked, and other technical confounders that need to be considered (e.g. off-target DNA contamination). Sorry that I can't provide more guidance than that.

- Stephane

**Comment by TaoHJiang** [comment]
> Hello,
> 
> In theory I don't see a reason why it wouldn't work, however, it is not been benchmarked at all for this use case. There may be parameters that need to be tweaked, and other technical confounders that need to be considered (e.g. off-target DNA contamination). Sorry that I can't provide more guidance than that.
> 
> * Stephane

Thanks for your reply, and what you're thinking about is exactly what I'm worried about. Now i attempt to deal with some ChIp-seq data, but you know the depth of these samples is generally not enough to search for ASB by using heterozygous loci .So i want to try haplotype. Unfortunately i don't know the parental genotypes of experimental individuals. Can you give me some advices for this problem? 
Thank you!

**Comment by TaoHJiang** [comment]
Thanks for your reply, and what you're thinking about is exactly what I'm worried about. Now i attempt to deal with some ChIp-seq data, but you know the depth of these samples is generally not enough to search for ASB by using heterozygous loci .So i want to try haplotype. Unfortunately i don't know the parental genotypes of experimental individuals. Can you give me some advices for this problem? 
Thank you!

**Comment by secastel** [comment]
Assuming these are humans, I would phase the VCF using a population based reference panel (e.g. 1000 Genomes, HRC, etc...), for example with https://imputationserver.sph.umich.edu/. Then use the phased VCF as input for phASER.

**Comment by TaoHJiang** [comment]
Thanks for your advice. I'll try it.
