### ISSUE TITLE
Issues with phaser-pop

### ISSUE THREAD

**Issue by lilyjiang94** [secastel/phaser#74]
Hi Developer,

I was trying to calculate aFCs by running phaser-pop with Whole Blood example data. But it gave me following error message:
<img width="696" alt="Screenshot 2022-02-03 at 11 01 08 PM" src="https://user-images.githubusercontent.com/70562647/152469745-09285e9d-3b80-4f2a-85af-142e7ee741db.png">

I used the exact same files provided in cis_var_example folder and downloaded phASER_WASP_GTEx_v8_matrix.gw_phased.txt.gz and phASER_GTEx_v8_merged.vcf.gz from GTEx and dbGaP. Could you help me with this? 

Thanks a lot!

Lily

**Comment by 7ehuang** [comment]
do you know if phASER_GTEx_v8_merged.vcf.gz  is still available on dbGaP? i can't seem to locate this file

**Comment by secastel** [comment]
Unfortunately I no longer have access to the GTEx dbGaP repository anymore, so I can't check. I'd suggest reaching out to someone at the GTEx portal about this: https://www.gtexportal.org/home/contact
