### ISSUE TITLE
phaser.py requires pysam

### ISSUE THREAD

**Issue by davetang** [secastel/phaser#76]
The [README](https://github.com/secastel/phaser/blob/master/phaser/README.md) lists the following dependencies for [phaser.py](https://github.com/secastel/phaser/blob/master/phaser/phaser.py):

>Runs on Python 2.7.x and has the following dependencies: [SciPy](http://www.scipy.org/), [NumPy](http://www.numpy.org/), [samtools](http://www.htslib.org/), [tabix](http://www.htslib.org/doc/tabix.html), [bedtools](http://bedtools.readthedocs.org/), [Cython](http://cython.org/)

But [pysam](https://pysam.readthedocs.io/en/latest/api.html) is also required.

**Comment by secastel** [comment]
Thanks for pointing this out, I have updated the README.
