### ISSUE TITLE
parameter '--no_gw_phase 0'

### ISSUE THREAD

**Issue by shiwobu** [secastel/phaser#79]
Dear Dr. Stephane:
Hello, I am a graduate student of Huazhong Agricultural University. I would like to ask you a question. Recently, when I was using the software phASER, I manually phased the VCF file. I don't want the software to phase again. I am following the [step-by-step tutorial](https://stephanecastel.wordpress.com/2017/02/15/how-to-generate-ase-data-with-phaser/) you wrote, I found the relevant parameter '--no_gw_phase 0' in tutorial, but I didn't find this parameter when running the software, and there is no such parameter in the python code. What should I do?
Thank you for sparing a time to read my message in the midst of pressing affairs.
Best wishes

**Comment by secastel** [comment]
Hello - phASER will change phase only of variants where the sequencing reads support an alternative phase. Unfortunately it is not possible to disable this functionality, as this step is required building the haplotype counts. The parameter you are referring to will not prevent phasing from occurring.

**Comment by shiwobu** [comment]
Thank you very much for your reply and help!
