### ISSUE TITLE
phaser_cis_var.py

### ISSUE THREAD

**Issue by Yang-Yingshan** [secastel/phaser#83]
Hello, thank you very much for providing such a good tool. I hope you can answer some mistakes in the process of using it. When using this phaser_cis_var.py script, you get an ERROR: ERROR: no phASER data read from input... check that chromsome naming is correct.. I am sure I am using input in bed.gz format. When I look at the script content, I find that when I change line 80 to change 1 to 3, it will run，I wonder if this will affect the result.

**Comment by secastel** [comment]
Hi there. Indeed this seems to be a bug and not quite sure how it wasn't identified before... I have pushed a change to fix the issue. I hope this solves the issue.
